import { useEffect } from 'react';
import FontUtility from '../../modules/Font/util';
import type { Template } from '../../modules/Template/template';
import HooksyLinkButton from './content/button';
import HooksyLinkHeaderContent from './content/header';
import HooksyLinkProfile from './content/profile';
import { LINK_TEMPLATE } from '../../lib/stores/hooksylink';

const HooksyLinkTemplate = () => {
  useEffect(() => LINK_TEMPLATE.set(template.link), []);

  return (
    <div
      className={`flex h-full w-full flex-col gap-4 overflow-y-auto p-5 ${
        FontUtility.getFontClass(template.theme.font.font_type) || 'font-sans'
      }`}
      style={{
        background: template.theme.background.color,
        color: template.theme.font.font_color,
      }}
    >
      <HooksyLinkProfile template={template} />

      <div className="flex flex-col gap-4">
        {template.content.map((content) =>
          content.type === 'HEADER' ? (
            <HooksyLinkHeaderContent
              key={content.content_id}
              content={content}
            />
          ) : content.type === 'BASE' ? (
            <HooksyLinkButton
              key={content.content_id}
              buttonSpec={template.theme.button}
              content={content}
            />
          ) : null,
        )}
      </div>
    </div>
  );
};

export default HooksyLinkTemplate;

const template: Template = {
  template_id: 123,
  link: 'https://hooksy.link/edricgalentino',
  title: 'Edric Galentino',
  description: 'Edric Galentino is a software engineer and a content creator.',
  profile_image: 'https://randomuser.me/api/portraits/men/18.jpg',
  content: [
    {
      content_id: 0,
      template_id: 123,
      user_id: 1,
      type: 'HEADER',
      title: 'IT IS ME BABY',
      link: '',
      is_active: true,
      is_deleted: false,
      clicks: 12,
      is_locked: false,
      //   is_prioritized: true,
      //   priority_type?: 'SPOTLIGHT' | 'ANIMATE',
      //   priority_animation?: 'POP' | 'BOUNCE' | 'SWIPE',
      is_prioritized: false,
      //   is_scheduled: false,
      //   start_show_link?: string,
      //   end_show_link?: string,
      // 	 timezone?: string,
      is_scheduled: false,
      created_at: '2022-01-01T00:00:00.000Z',
      updated_at: '2022-01-01T00:00:00.000Z',
    },
    {
      content_id: 1,
      template_id: 123,
      user_id: 1,
      type: 'BASE',
      title: 'Instagram',
      link: 'https://instagram.com/edricgalentino',
      is_active: true,
      is_deleted: false,
      clicks: 12,
      is_locked: false,
      //   is_prioritized: true,
      //   priority_type?: 'SPOTLIGHT' | 'ANIMATE',
      //   priority_animation?: 'POP' | 'BOUNCE' | 'SWIPE',
      is_prioritized: true,
      priority_type: 'SPOTLIGHT',
      //   is_scheduled: false,
      //   start_show_link?: string,
      //   end_show_link?: string,
      // 	 timezone?: string,
      is_scheduled: false,
      created_at: '2022-01-01T00:00:00.000Z',
      updated_at: '2022-01-01T00:00:00.000Z',
    },
    {
      content_id: 2,
      template_id: 123,
      user_id: 1,
      type: 'BASE',
      title: 'YouTube',
      link: 'https://youtube.com/edricgalentino',
      is_active: true,
      is_deleted: false,
      clicks: 12,
      is_locked: false,
      //   is_prioritized: true,
      //   priority_type?: 'SPOTLIGHT' | 'ANIMATE',
      //   priority_animation?: 'POP' | 'BOUNCE' | 'SWIPE',
      is_prioritized: true,
      priority_type: 'ANIMATE',
      priority_animation: 'POP',
      //   is_scheduled: false,
      //   start_show_link?: string,
      //   end_show_link?: string,
      // 	 timezone?: string,
      is_scheduled: false,
      created_at: '2022-01-01T00:00:00.000Z',
      updated_at: '2022-01-01T00:00:00.000Z',
    },
    {
      content_id: 3,
      template_id: 123,
      user_id: 1,
      type: 'BASE',
      title: 'LinkedIn',
      link: 'https://linkedin.com/in/edricgalentino',
      is_active: true,
      is_deleted: false,
      clicks: 12,
      is_locked: false,
      is_prioritized: true,
      priority_type: 'ANIMATE',
      priority_animation: 'BOUNCE',
      //   is_scheduled: false,
      //   start_show_link?: string,
      //   end_show_link?: string,
      // 	 timezone?: string,
      is_scheduled: false,
      created_at: '2022-01-01T00:00:00.000Z',
      updated_at: '2022-01-01T00:00:00.000Z',
    },
    {
      content_id: 3,
      template_id: 123,
      user_id: 1,
      type: 'BASE',
      title: 'LinkedIn 2',
      link: 'https://linkedin.com/in/edricgalentino',
      thumbnail: 'https://randomuser.me/api/portraits/men/16.jpg',
      is_active: true,
      is_deleted: false,
      clicks: 12,
      is_locked: false,
      is_prioritized: true,
      priority_type: 'ANIMATE',
      priority_animation: 'SWIPE',
      //   is_scheduled: false,
      //   start_show_link?: string,
      //   end_show_link?: string,
      // 	 timezone?: string,
      is_scheduled: false,
      created_at: '2022-01-01T00:00:00.000Z',
      updated_at: '2022-01-01T00:00:00.000Z',
    },
    // scheduled content
    {
      content_id: 4,
      template_id: 123,
      user_id: 1,
      type: 'BASE',
      title: 'You only can see me on 17:00 - 18:00',
      link: 'https://linkedin.com/in/edricgalentino',
      is_active: true,
      is_deleted: false,
      clicks: 12,
      is_locked: false,
      is_prioritized: false,
      is_scheduled: true,
      start_show_link: '2024-07-28T17:00:00.000Z',
      end_show_link: '2024-07-28T18:00:00.000Z',
      timezone: 'Asia/Jakarta',
      created_at: '2022-01-01T00:00:00.000Z',
      updated_at: '2022-01-01T00:00:00.000Z',
    },
    {
      content_id: 0,
      template_id: 123,
      user_id: 1,
      type: 'HEADER',
      title: 'IT IS ME BABY',
      link: '',
      is_active: true,
      is_deleted: false,
      clicks: 12,
      is_locked: false,
      //   is_prioritized: true,
      //   priority_type?: 'SPOTLIGHT' | 'ANIMATE',
      //   priority_animation?: 'POP' | 'BOUNCE' | 'SWIPE',
      is_prioritized: false,
      //   is_scheduled: false,
      //   start_show_link?: string,
      //   end_show_link?: string,
      // 	 timezone?: string,
      is_scheduled: false,
      created_at: '2022-01-01T00:00:00.000Z',
      updated_at: '2022-01-01T00:00:00.000Z',
    },
    {
      content_id: 1,
      template_id: 123,
      user_id: 1,
      type: 'BASE',
      title: 'Instagram',
      link: 'https://instagram.com/edricgalentino',
      is_active: true,
      is_deleted: false,
      clicks: 12,
      is_locked: false,
      //   is_prioritized: true,
      //   priority_type?: 'SPOTLIGHT' | 'ANIMATE',
      //   priority_animation?: 'POP' | 'BOUNCE' | 'SWIPE',
      is_prioritized: true,
      priority_type: 'SPOTLIGHT',
      //   is_scheduled: false,
      //   start_show_link?: string,
      //   end_show_link?: string,
      // 	 timezone?: string,
      is_scheduled: false,
      created_at: '2022-01-01T00:00:00.000Z',
      updated_at: '2022-01-01T00:00:00.000Z',
    },
    {
      content_id: 2,
      template_id: 123,
      user_id: 1,
      type: 'BASE',
      title: 'YouTube',
      link: 'https://youtube.com/edricgalentino',
      is_active: true,
      is_deleted: false,
      clicks: 12,
      is_locked: false,
      //   is_prioritized: true,
      //   priority_type?: 'SPOTLIGHT' | 'ANIMATE',
      //   priority_animation?: 'POP' | 'BOUNCE' | 'SWIPE',
      is_prioritized: true,
      priority_type: 'ANIMATE',
      priority_animation: 'POP',
      //   is_scheduled: false,
      //   start_show_link?: string,
      //   end_show_link?: string,
      // 	 timezone?: string,
      is_scheduled: false,
      created_at: '2022-01-01T00:00:00.000Z',
      updated_at: '2022-01-01T00:00:00.000Z',
    },
    {
      content_id: 3,
      template_id: 123,
      user_id: 1,
      type: 'BASE',
      title: 'LinkedIn',
      link: 'https://linkedin.com/in/edricgalentino',
      is_active: true,
      is_deleted: false,
      clicks: 12,
      is_locked: false,
      is_prioritized: true,
      priority_type: 'ANIMATE',
      priority_animation: 'BOUNCE',
      //   is_scheduled: false,
      //   start_show_link?: string,
      //   end_show_link?: string,
      // 	 timezone?: string,
      is_scheduled: false,
      created_at: '2022-01-01T00:00:00.000Z',
      updated_at: '2022-01-01T00:00:00.000Z',
    },
    {
      content_id: 3,
      template_id: 123,
      user_id: 1,
      type: 'BASE',
      title: 'LinkedIn 2',
      link: 'https://linkedin.com/in/edricgalentino',
      thumbnail: 'https://randomuser.me/api/portraits/men/16.jpg',
      is_active: true,
      is_deleted: false,
      clicks: 12,
      is_locked: false,
      is_prioritized: true,
      priority_type: 'ANIMATE',
      priority_animation: 'SWIPE',
      //   is_scheduled: false,
      //   start_show_link?: string,
      //   end_show_link?: string,
      // 	 timezone?: string,
      is_scheduled: false,
      created_at: '2022-01-01T00:00:00.000Z',
      updated_at: '2022-01-01T00:00:00.000Z',
    },
    // scheduled content
    {
      content_id: 4,
      template_id: 123,
      user_id: 1,
      type: 'BASE',
      title: 'You only can see me on 17:00 - 18:00',
      link: 'https://linkedin.com/in/edricgalentino',
      is_active: true,
      is_deleted: false,
      clicks: 12,
      is_locked: false,
      is_prioritized: false,
      is_scheduled: true,
      start_show_link: '2024-07-28T17:00:00.000Z',
      end_show_link: '2024-07-28T18:00:00.000Z',
      timezone: 'Asia/Jakarta',
      created_at: '2022-01-01T00:00:00.000Z',
      updated_at: '2022-01-01T00:00:00.000Z',
    },
    {
      content_id: 0,
      template_id: 123,
      user_id: 1,
      type: 'HEADER',
      title: 'IT IS ME BABY',
      link: '',
      is_active: true,
      is_deleted: false,
      clicks: 12,
      is_locked: false,
      //   is_prioritized: true,
      //   priority_type?: 'SPOTLIGHT' | 'ANIMATE',
      //   priority_animation?: 'POP' | 'BOUNCE' | 'SWIPE',
      is_prioritized: false,
      //   is_scheduled: false,
      //   start_show_link?: string,
      //   end_show_link?: string,
      // 	 timezone?: string,
      is_scheduled: false,
      created_at: '2022-01-01T00:00:00.000Z',
      updated_at: '2022-01-01T00:00:00.000Z',
    },
    {
      content_id: 1,
      template_id: 123,
      user_id: 1,
      type: 'BASE',
      title: 'Instagram',
      link: 'https://instagram.com/edricgalentino',
      is_active: true,
      is_deleted: false,
      clicks: 12,
      is_locked: false,
      //   is_prioritized: true,
      //   priority_type?: 'SPOTLIGHT' | 'ANIMATE',
      //   priority_animation?: 'POP' | 'BOUNCE' | 'SWIPE',
      is_prioritized: true,
      priority_type: 'SPOTLIGHT',
      //   is_scheduled: false,
      //   start_show_link?: string,
      //   end_show_link?: string,
      // 	 timezone?: string,
      is_scheduled: false,
      created_at: '2022-01-01T00:00:00.000Z',
      updated_at: '2022-01-01T00:00:00.000Z',
    },
    {
      content_id: 2,
      template_id: 123,
      user_id: 1,
      type: 'BASE',
      title: 'YouTube',
      link: 'https://youtube.com/edricgalentino',
      is_active: true,
      is_deleted: false,
      clicks: 12,
      is_locked: false,
      //   is_prioritized: true,
      //   priority_type?: 'SPOTLIGHT' | 'ANIMATE',
      //   priority_animation?: 'POP' | 'BOUNCE' | 'SWIPE',
      is_prioritized: true,
      priority_type: 'ANIMATE',
      priority_animation: 'POP',
      //   is_scheduled: false,
      //   start_show_link?: string,
      //   end_show_link?: string,
      // 	 timezone?: string,
      is_scheduled: false,
      created_at: '2022-01-01T00:00:00.000Z',
      updated_at: '2022-01-01T00:00:00.000Z',
    },
    {
      content_id: 3,
      template_id: 123,
      user_id: 1,
      type: 'BASE',
      title: 'LinkedIn',
      link: 'https://linkedin.com/in/edricgalentino',
      is_active: true,
      is_deleted: false,
      clicks: 12,
      is_locked: false,
      is_prioritized: true,
      priority_type: 'ANIMATE',
      priority_animation: 'BOUNCE',
      //   is_scheduled: false,
      //   start_show_link?: string,
      //   end_show_link?: string,
      // 	 timezone?: string,
      is_scheduled: false,
      created_at: '2022-01-01T00:00:00.000Z',
      updated_at: '2022-01-01T00:00:00.000Z',
    },
    {
      content_id: 3,
      template_id: 123,
      user_id: 1,
      type: 'BASE',
      title: 'LinkedIn 2',
      link: 'https://linkedin.com/in/edricgalentino',
      thumbnail: 'https://randomuser.me/api/portraits/men/16.jpg',
      is_active: true,
      is_deleted: false,
      clicks: 12,
      is_locked: false,
      is_prioritized: true,
      priority_type: 'ANIMATE',
      priority_animation: 'SWIPE',
      //   is_scheduled: false,
      //   start_show_link?: string,
      //   end_show_link?: string,
      // 	 timezone?: string,
      is_scheduled: false,
      created_at: '2022-01-01T00:00:00.000Z',
      updated_at: '2022-01-01T00:00:00.000Z',
    },
    // scheduled content
    {
      content_id: 4,
      template_id: 123,
      user_id: 1,
      type: 'BASE',
      title: 'You only can see me on 17:00 - 18:00',
      link: 'https://linkedin.com/in/edricgalentino',
      is_active: true,
      is_deleted: false,
      clicks: 12,
      is_locked: false,
      is_prioritized: false,
      is_scheduled: true,
      start_show_link: '2024-07-28T17:00:00.000Z',
      end_show_link: '2024-07-28T18:00:00.000Z',
      timezone: 'Asia/Jakarta',
      created_at: '2022-01-01T00:00:00.000Z',
      updated_at: '2022-01-01T00:00:00.000Z',
    },
  ],
  user_id: 1,
  created_at: '2022-01-01T00:00:00.000Z',
  updated_at: '2022-01-01T00:00:00.000Z',
  is_deleted: false,
  is_private: false,
  is_watermark_removed: false,
  like: 100,
  view: 1000,
  status: 'PUBLISH',
  type: 'SHARED',
  theme: {
    theme_id: 1,
    template_id: 123,
    background: {
      background_id: 1,
      theme_id: 1,
      color: '#f8f4e1',
      dekstop_color: '#f8f4e1',
      type: 'FLAT COLOUR',
      created_at: '2022-01-01T00:00:00.000Z',
      updated_at: '2022-01-01T00:00:00.000Z',
    },
    button: {
      button_id: 1,
      theme_id: 1,
      // color: '#f8f4e1',
      // font_color: '#991b1b',
      // rounded: 'NOT',
      // type: 'HARD SHADOW',
      // rounded: 'FULL',
      // type: 'SOFT SHADOW',
      font_color: '#f8f4e1',
      color: '#991b1b',
      rounded: 'MEDIUM',
      type: 'FILL',
      created_at: '2022-01-01T00:00:00.000Z',
      updated_at: '2022-01-01T00:00:00.000Z',
    },
    font: {
      font_id: 1,
      theme_id: 1,
      font_color: '#000000',
      font_type: 'Montserrat',
      created_at: '2022-01-01T00:00:00.000Z',
      updated_at: '2022-01-01T00:00:00.000Z',
    },
    created_at: '2022-01-01T00:00:00.000Z',
    updated_at: '2022-01-01T00:00:00.000Z',
  },
};
